export { default as lbbl_ani } from './lbbl.gif'
export { default as test_photo } from './test_photo.jpeg'
export { default as introduce_photo } from './introduce_photo.jpeg'
export { default as test1 } from './test1.JPG'
export { default as test2 } from './test2.JPG'
export { default as test3 } from './test3.JPG'
export { default as test4 } from './test4.JPG'
export { default as test5 } from './test5.JPG'
export { default as test6 } from './test6.JPG'

export { default as green_arrow } from './green_arrow.png'
export { default as main_picture } from './main_picture.png'
export { default as main_picture2 } from './main_picture2.png'
export { default as orange_button } from './orange_send_button.png'
export { default as white_star_1 } from './white_visual_1.png'
export { default as white_star_2 } from './white_visual_2.png'
export { default as orange_mark } from './orange_mark.png'

export { default as kor_gray } from './kor_gray.png'
export { default as kor_orange } from './kor_orange.png'
export { default as eng_gray } from './eng_gray.png'
export { default as eng_orange } from './eng_orange.png'
export { default as opensea } from './opensea.png'

export { default as logo } from './logo.png'
